import uniqueId from 'lodash/uniqueId';

export default (response) => {
  const parser = new DOMParser();
  const doc = parser.parseFromString(response.data, 'text/xml');
  const items = doc.querySelectorAll('item');
  if (document.querySelector('section') === null) {
    const section = document.createElement('section');
    section.classList.add('container-fluid', 'container-xxl', 'p-5');
    const div = document.createElement('div');
    div.classList.add('row');
    section.append(div);
    const div1 = document.createElement('div');
    div1.classList.add('col-md-10', 'col-lg-8', 'order-1', 'mx-auto', 'posts');
    div.append(div1);
    const div2 = document.createElement('div');
    div2.classList.add('card', 'border-0');
    div1.append(div2);
    const div3 = document.createElement('div');
    div3.classList.add('card-body');
    div2.append(div3);
    const h2 = document.createElement('h2');
    h2.classList.add('card-title', 'h4');
    h2.textContent = 'Посты';
    div3.append(h2);
    const ul = document.createElement('ul');
    ul.classList.add('list-group', 'border-0', 'rounded-0');
    div2.append(ul);
    items.forEach((item) => {
      const id = uniqueId();
      const li = document.createElement('li');
      li.classList.add('list-group-item', 'd-flex', 'justify-content-between', 'align-items-start', 'border-0', 'border-end-0');
      const title = item.querySelector('title').textContent;
      const href = item.querySelector('link').textContent;
      const description = item.querySelector('description').textContent;
      const a = document.createElement('a');
      a.setAttribute('href', href);
      a.classList.add('fw-bold');
      a.setAttribute('data-id', id);
      a.setAttribute('target', '_blank');
      a.setAttribute('rel', 'noopener noreferer');
      a.textContent = title;
      li.append(a);
      const button = document.createElement('button');
      button.setAttribute('type', 'button');
      button.classList.add('btn', 'btn-outline-primary', 'btn-sm');
      button.setAttribute('data-id', id);
      button.setAttribute('data-bs-toggle', 'modal');
      button.setAttribute('data-bs-target', '#modal');
      button.textContent = 'Просмотр';
      li.append(button);
      ul.append(li);
    });
    document.body.append(section);
  } else {
    const ul = document.querySelector('.list-group');
    items.forEach((item) => {
      const id = uniqueId();
      const li = document.createElement('li');
      li.classList.add('list-group-item', 'd-flex', 'justify-content-between', 'align-items-start', 'border-0', 'border-end-0');
      const title = item.querySelector('title').textContent;
      const href = item.querySelector('link').textContent;
      const description = item.querySelector('description').textContent;
      const a = document.createElement('a');
      a.setAttribute('href', href);
      a.classList.add('fw-bold');
      a.setAttribute('data-id', id);
      a.setAttribute('target', '_blank');
      a.setAttribute('rel', 'noopener noreferer');
      a.textContent = title;
      li.append(a);
      const button = document.createElement('button');
      button.setAttribute('type', 'button');
      button.classList.add('btn', 'btn-outline-primary', 'btn-sm');
      button.setAttribute('data-id', id);
      button.setAttribute('data-bs-toggle', 'modal');
      button.setAttribute('data-bs-target', '#modal');
      button.textContent = 'Просмотр';
      li.append(button);
      ul.prepend(li);
    });
  }
};
